# Generated by Django 5.0.7 on 2024-11-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='img_bano',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/banos/'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='img_cama',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/camas/'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='img_terraza',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/terrazas/'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
    ]
