# Generated by Django 5.0.7 on 2024-11-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_habitacion_img_bano_habitacion_img_cama_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='img_bano',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='img_cama',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='img_terraza',
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(choices=[('I', 'Individual'), ('D', 'Doble'), ('S', 'Suite'), ('F', 'Familiar')], max_length=1),
        ),
    ]
